// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {keyboard} from '../models';

export function GetKeyboardKeys():Promise<Array<keyboard.Key>>;

export function GetKeyboardMatrix():Promise<Array<keyboard.Key>>;

export function Reload():Promise<void>;
