// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetConnectedStatus() {
  return window['go']['main']['App']['GetConnectedStatus']();
}

export function GetKeyboardKeys() {
  return window['go']['main']['App']['GetKeyboardKeys']();
}

export function GetKeyboardMatrix() {
  return window['go']['main']['App']['GetKeyboardMatrix']();
}

export function Reload() {
  return window['go']['main']['App']['Reload']();
}
